- name: "config content views | Create or update content views"
  theforeman.foreman.content_view:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_server_url }}"
    name: "{{ item.name }}"
    organization: "{{ satellite_organization }}"
    repositories: "{{ item.repos | json_query(_query) }}"
  with_items: "{{ satellite_all_cvs }}"
  vars:
    _query: '[*].{name: reponame, product: product}'
  notify: handler - publish content views

- name: Flush handlers
  meta: flush_handlers

- name: "config content views | Create a composite content view"
  theforeman.foreman.content_view:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_server_url }}"
    name: "{{ item.name }}"
    organization: "{{ satellite_organization }}"
    composite: true
    auto_publish: true
    components: "{{ item.components }}"
  with_items: "{{ satellite_all_ccvs }}"
  notify: handler - publish composite content views
  when: satellite_all_ccvs is defined

- name: Flush handlers
  meta: flush_handlers
