---
- name: Check if amazon-id.conf exists
  stat:
    path: /etc/yum/pluginconf.d/amazon-id.conf
  register: _amazon_id_stat

- name: RHSM Subscribe | Disable amazon-id.conf
  lineinfile:
    path: /etc/yum/pluginconf.d/amazon-id.conf
    regexp: '^enabled=1'
    line: enabled=0
    backrefs: yes
  when: _amazon_id_stat.stat.exists

- name: RHSM Subscribe | Get a list of all the files in /etc/yum.repos.d
  find:
    paths: 
      - /etc/yum.repos.d
    patterns: "*.repo"
  register: repo_files

- name: RHSM Subscribe | Remove any file in /etc/yum.repos.d that isn't redhat.repo
  file:
    path: "{{ item.path }}"
    state: absent
  when: item.path != "/etc/yum.repos.d/redhat.repo"
  with_items: "{{ repo_files.files }}"

# - name: RHSM Subscribe | remove old subscription
#   redhat_subscription:
#     state: absent

# - name: RHSM Subscribe | remove old rpms from Satellite 6
#   package:
#     name: "katello-ca-consumer-*.noarch"
#     state: absent

# - name: RHSM Subscribe | Using an Activation Key for register to Red Hat CDN
#   redhat_subscription:
#     state: present
#     activationkey: "{{ satellite_rhn_activation_key }}"
#     org_id: "{{ satellite_rhn_org }}"
#     pool: '^(Red Hat Satellite Infrastructure Subscription)$'
#     force_register: yes
#   when: satellite_rhn_activation_key | length > 0

# - name: RHSM Subscribe | Using RHN User/Password Red Hat CDN
#   redhat_subscription:
#     state: present
#     username: "{{ satellite_rhn_username }}"
#     password: "{{ satellite_rhn_password }}"
#     pool: '^(Red Hat Satellite Infrastructure Subscription)$'
#     force_register: yes
#   when: satellite_rhn_activation_key | length == 0

#Enabling the repos
- name: "RHSM Subscribe | Enabling the satellite repos"
  command: "/usr/sbin/subscription-manager repos --disable '*' --enable
    rhel-7-server-satellite-{{ satellite_deployment_version }}-rpms
    --enable rhel-7-server-rpms --enable rhel-server-rhscl-7-rpms --enable rhel-7-server-satellite-maintenance-6-rpms --enable rhel-7-server-ansible-2.8-rpms"
  tags:
    - "rhn"
    - "skip_ansible_lint" # ANSIBLE0012
