- name: install | get package facts
  package_facts:
    manager: auto

- name: install | install satellite package
  package:
    name: "{{ satellite_packages }}"
    state: present
  when: "'satellite' not in ansible_facts.packages"

# copy template file with sceniario options and only run installer if changed
- name: install | copy installer script
  template:
    src: satellite_install.sh.j2
    dest: /root/satellite_install.sh
    owner: root
    group: root
    mode: 0640
  notify: run_installer

- meta: flush_handlers

# Perfomance tune the satellite installation
  - name: Activation of the performance tuning
    shell: satellite-installer --tuning "{{ satellite_tuning }}"
