---
- name: Pull down manifest
  get_url:
    url: https://subscription.rhsm.redhat.com/subscription/consumers/{{ manifest_uuid }}/export
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    dest: /opt/satellite_manifest.zip
    validate_certs: no
    
- name: "Upload the manifest"
  theforeman.foreman.katello_manifest:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "https://{{ ansible_fqdn }}"
    organization: "{{ satellite_organization }}"
    state: present
    manifest_path: "/opt/satellite_manifest.zip" 
