- name: satellite settings | common settings
  theforeman.foreman.foreman_setting:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_server_url }}"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - "{{ satellite_settings }}"
