# copy template file with sceniario options and only run installer if changed
- name: install | copy installer script
  template:
    src: satellite_install.sh.j2
    dest: /root/satellite_install.sh
    owner: root
    group: root
    mode: 0640
  notify: run_installer

- meta: flush_handlers

# Perfomance tune the satellite installation
- name: Move performance tuning yaml to /etc/foreman-installer/custom-hiera.yaml
  copy:
    src: files/custom-hiera.yaml
    dest: /etc/foreman-installer/custom-hiera.yaml
    owner: root
    group: root

- name: Activation of the performance tuning
  shell: satellite-installer
    
