# task file for install
- name: main | Register to RHN
  import_tasks: 1_rhsm_subscribe.yml
  
- name: main | Patching system
  import_tasks: 2_patch.yml
  
- name: main | Configure LV
  import_tasks: 3_storage_config.yml

- name: main | install theforeman prereq
  import_tasks: 4_theforeman.yml

- name: main | install satellite
  import_tasks: 5_install.yml

- name: main | set satellite settings
  import_tasks: 6_settings.yml

- name: main | uploading manifests
  import_tasks: 7_manifest.yml
