- name: testing
  include_tasks:
    file: 00_test.yml
    apply:
      tags: testing
  tags:
    - testing
    - never
    
# task file for install
- name: main | Register to RHN
  include_tasks:
    file: 1_rhsm_subscribe.yml
    apply:
      tags: serverprep
  tags:
    - serverprep
    
- name: main | Configure system
  include_tasks:
    file: 2_sysconfig.yml
    apply:
      tags: serverprep
  tags:
    - serverprep

- name: main | Configure LV
  include_tasks:
    file: 3_storage_config.yml
    apply:
      tags: serverprep
  tags:
    - serverprep

- name: main | Installing Satellite Packages
  include_tasks:
    file: 4_install_packages.yml 
    apply:
      tags: satinstall
  tags:
    - satinstall

- name: main | install theforeman prereq
  include_tasks:
    file: 5_theforeman.yml
    apply:
      tags: satinstall
  tags:
    - satinstall

- name: main | Create Certs and CSR
  include_tasks:
    file: 6.1_prep-custom-certs.yml
    apply:
      tags: satcerts
  tags:
    - satcerts
  when: satellite_certs_generate

- name: main | Configure provided Certs
  include_tasks:
    file: 6.2_install-provided-certs.yml
    apply:
      tags: satcerts
  tags:
    - satcerts
  when: not satellite_certs_generate

- name: main | Test Certs
  include_tasks:
    file: 6.10_test-certs.yml
    apply:
      tags: satcerts
  tags:
    - satcerts

- name: main | fix hosts file
  include_tasks:
    file: 7_dns_config.yml
    apply:
      tags: serverprep
  tags:
    - serverprep

- name: main | install satellite
  include_tasks:
    file: 8_install.yml
    apply:
      tags: satinstall
  tags:
    - satinstall

- name: main | set satellite settings
  include_tasks:
    file: 9_settings.yml
    apply:
      tags: satconfigure
  tags:
    - satconfigure

- name: main | uploading manifests
  include_tasks:
    file: 10_manifest.yml
    apply:
      tags: 
        - satcontent
        - satcontentsync
  tags:
    - satcontent
    - satcontentsync

- name: main | enable required repositories
  include_tasks:
    file: 11_enablerepos.yml
    apply:
      tags: satcontent
  tags:
    - satcontent

- name: main | Sync repositories
  include_tasks:
    file: 12_repo_sync.yml
    apply:
      tags: 
        - satcontent
        - satcontentsync
  tags:
    - satcontent
    - satcontentsync

- name: main | create Content Views
  include_tasks:
    file: 13_content_views.yml
    apply:
      tags: satcontent
  tags:
    - satcontent

- name: main | Create host collections
  include_tasks:
    file: 14_host_collections.yml
    apply:
      tags: satcontent
  tags:
    - satcontent

- name: main | Create Activation Key
  include_tasks:
    file: 15_activation_keys.yml
    apply:
      tags: satcontent
  tags:
    - satcontent
