- name: run_installer
  command: >-
    satellite-installer --scenario satellite
    --foreman-initial-admin-username "{{ satellite_admin_username }}"
    {{ satellite_options }}
  register: installer_output

- name:
  debug:
    var: installer_output
